Using cuda device
Traceback (most recent call last):
  File "/home/kpatherya3/anaconda3/envs/causal_copy/lib/python3.7/site-packages/stable_baselines3/common/vec_env/patch_gym.py", line 40, in _patch_env
    import shimmy  # pytype: disable=import-error
ModuleNotFoundError: No module named 'shimmy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mfrl_scratch.py", line 151, in <module>
    wandb_config=wandb_config
  File "mfrl_scratch.py", line 89, in train_policy
    seed=seed_num
  File "/home/kpatherya3/anaconda3/envs/causal_copy/lib/python3.7/site-packages/stable_baselines3/sac/sac.py", line 145, in __init__
    support_multi_env=True,
  File "/home/kpatherya3/anaconda3/envs/causal_copy/lib/python3.7/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 124, in __init__
    supported_action_spaces=supported_action_spaces,
  File "/home/kpatherya3/anaconda3/envs/causal_copy/lib/python3.7/site-packages/stable_baselines3/common/base_class.py", line 169, in __init__
    env = self._wrap_env(env, self.verbose, monitor_wrapper)
  File "/home/kpatherya3/anaconda3/envs/causal_copy/lib/python3.7/site-packages/stable_baselines3/common/base_class.py", line 216, in _wrap_env
    env = _patch_env(env)
  File "/home/kpatherya3/anaconda3/envs/causal_copy/lib/python3.7/site-packages/stable_baselines3/common/vec_env/patch_gym.py", line 47, in _patch_env
    ) from e
ImportError: Missing shimmy installation. You an OpenAI Gym environment. Stable-Baselines3 (SB3) has transitioned to using Gymnasium internally. In order to use OpenAI Gym environments with SB3, you need to install shimmy (`pip install 'shimmy>=0.2.1'`).
